wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.16
    start_time: 1680563354.827477
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 23
      4: 3.8.16
      5: 0.14.0
      8:
      - 2
      - 5
