wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1698021650.276577
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.13
      5: 0.13.2
      8:
      - 5
active:
  desc: null
  value: 0
alpha_active:
  desc: null
  value: 1.0
alpha_dirichlet:
  desc: null
  value: 1
backend:
  desc: null
  value: sp
batch_size:
  desc: null
  value: 301
client_id_list:
  desc: null
  value: '[]'
client_num_in_total:
  desc: null
  value: 100
client_num_per_round:
  desc: null
  value: 10
client_optimizer:
  desc: null
  value: CosAnnealing
comm_round:
  desc: null
  value: 75
config_version:
  desc: null
  value: dev
data_cache_dir:
  desc: null
  value: /home/shubham/fedml_data
dataset:
  desc: null
  value: CIFAR100
enable_tracking:
  desc: null
  value: false
enable_wandb:
  desc: null
  value: true
epochs:
  desc: null
  value: 4
federated_optimizer:
  desc: null
  value: FedAvg
frequency_of_the_test:
  desc: null
  value: 1
gpu_id:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 0.1
local_rank:
  desc: null
  value: 0
mlops_api_key:
  desc: null
  value: c9356b9c4ce44363bb66366b210201
mlops_project_name:
  desc: null
  value: simulation_2
mlops_run_name:
  desc: null
  value: fedml_torch_fedavg_COCP
model:
  desc: null
  value: RESNET_18
momentum:
  desc: null
  value: 0.9
node_rank:
  desc: null
  value: 0
num_groups:
  desc: null
  value: 5
overlap_num:
  desc: null
  value: 5
overlap_percentage:
  desc: null
  value: 1.0
partition_alpha:
  desc: null
  value: 0.5
partition_method:
  desc: null
  value: hetero
random_seed:
  desc: null
  value: 0
rank:
  desc: null
  value: 0
role:
  desc: null
  value: client
run_device_id:
  desc: null
  value: '0'
run_id:
  desc: null
  value: '0'
run_name:
  desc: null
  value: E4_R75_LRe-1_Dir:1_Overlap:5
sampling_fun:
  desc: null
  value: client_sampling_cyclic_noOverlap_pattern
sys_perf_profiling:
  desc: null
  value: true
training_type:
  desc: null
  value: simulation
using_gpu:
  desc: null
  value: true
using_mlops:
  desc: null
  value: false
var_epoch:
  desc: null
  value: 0
wandb_entity:
  desc: null
  value: shubham22124
wandb_key:
  desc: null
  value: d99d2566208f899b41fe157bc466bece6d1789e2
wandb_project:
  desc: null
  value: Cyclic and Overlapping Client Participation in Federated Setting
weight_decay:
  desc: null
  value: 0.0005
worker_num:
  desc: null
  value: 10
yaml_config_file:
  desc: null
  value: fedml_config.yaml
yaml_paths:
  desc: null
  value:
  - fedml_config.yaml
