comm_args:
  backend: sp
common_args:
  AdaptiveDecay: 2
  active: 0
  alpha_active: 1.0
  alpha_dirichlet: 0.05
  config_version: dev
  dirichlet_seed: 993522575
  group_norm_size: 0
  group_wise_models: true
  lr_update_freq: 5
  mlops_api_key: c9356b9c4ce44363bb66366b210201
  mlops_project_name: simulation_2
  mlops_run_name: fedml_torch_fedavg_COCP
  overlap_num: 7
  overlap_percentage: 1.0
  random_seed: 0
  sampling_fun: client_sampling_cyclic_overlap_pattern
  training_type: simulation
  var_epoch: 0
data_args:
  data_cache_dir: ~/fedml_data
  dataset: CIFAR100
  partition_alpha: 0.5
  partition_method: hetero
device_args:
  gpu_id: 0
  using_gpu: true
model_args:
  model: RESNET_18
tracking_args:
  enable_tracking: false
  enable_wandb: true
  run_name: Dir:0.05_Overlap:7_Dataset:CIFAR100_Remark:Pretrained
  wandb_entity: shubham22124
  wandb_key: d99d2566208f899b41fe157bc466bece6d1789e2
  wandb_project: Group_VS_Global_Pretrained
train_args:
  batch_size: 32
  client_id_list: '[]'
  client_num_in_total: 100
  client_num_per_round: 10
  client_optimizer: sgd
  comm_round: 1500
  epochs: 1
  federated_optimizer: FedAvg
  learning_rate: 0.2
  momentum: 0.9
  num_groups: 5
  server_lr: 0.01
  server_optimizer: Adam
  weight_decay: 1.0e-05
validation_args:
  frequency_of_the_test: 1
