comm_args:
  backend: sp
common_args:
  AdaptiveDecay: 10
  active: 0
  alpha_active: 1.0
  alpha_dirichlet: 1.0
  config_version: dev
  dirichlet_seed: 993522575
  group_norm_size: 0
  group_wise_models: false
  lr_update_freq: 2
  mlops_api_key: c9356b9c4ce44363bb66366b210201
  mlops_project_name: simulation_2
  mlops_run_name: fedml_torch_fedavg_COCP
  overlap_num: 5
  overlap_percentage: 1.0
  random_seed: 0
  sampling_fun: cyclic_overlap_pattern
  training_type: simulation
  var_epoch: 0
data_args:
  data_cache_dir: ~/fedml_data
  dataset: CIFAR10
  partition_alpha: 0.5
  partition_method: hetero
device_args:
  gpu_id: 2
  using_gpu: true
model_args:
  model: RESNET_18
tracking_args:
  enable_tracking: false
  enable_wandb: true
  run_name: Dir:1.0_Strategy:cyclic_overlap_pattern_Overlap:5_Dataset:CIFAR10_Remark:Participation_Normalised_Cheating
  wandb_entity: shubham22124
  wandb_key: d99d2566208f899b41fe157bc466bece6d1789e2
  wandb_project: Cyclic and Overlapping Client Participation(Federated) CIFAR10
train_args:
  batch_size: 64
  client_id_list: '[]'
  client_num_in_total: 100
  client_num_per_round: 10
  client_optimizer: sgd
  comm_round: 500
  epochs: 2
  federated_optimizer: FedAvg
  learning_rate: 0.1
  momentum: 0.9
  num_groups: 5
  weight_decay: 1.0e-05
validation_args:
  frequency_of_the_test: 1
