comm_args:
  backend: sp
common_args:
  AdaptiveDecay: 6
  active: 0
  alpha_active: 1.0
  alpha_dirichlet: 0.3
  config_version: dev
  dirichlet_seed: 3087732978
  group_norm_size: 0
  lr_update_freq: 8
  mlops_api_key: c9356b9c4ce44363bb66366b210201
  mlops_project_name: simulation_2
  mlops_run_name: fedml_torch_fedavg_COCP
  overlap_num: 0
  overlap_percentage: 1.0
  random_seed: 0
  sampling_fun: _client_sampling
  training_type: simulation
  var_epoch: 0
data_args:
  data_cache_dir: ~/fedml_data
  dataset: CIFAR100
  partition_alpha: 0.5
  partition_method: hetero
device_args:
  gpu_id: 3
  using_gpu: true
model_args:
  model: RESNET_18
tracking_args:
  enable_tracking: false
  enable_wandb: true
  run_name: E:2_R:500_Dir:0.3_RandomSampling_AdaptiveDecay:6_Freq:8
  using_mlops: false
  wandb_entity: shubham22124
  wandb_key: d99d2566208f899b41fe157bc466bece6d1789e2
  wandb_project: Cyclic and Overlapping Client Participation(Federated) 5
train_args:
  batch_size: 32
  client_id_list: '[]'
  client_num_in_total: 100
  client_num_per_round: 10
  client_optimizer: CosAnnealing
  comm_round: 500
  epochs: 2
  federated_optimizer: FedAvg
  learning_rate: 0.1
  momentum: 0.9
  num_groups: 5
  weight_decay: 1.0e-05
validation_args:
  frequency_of_the_test: 1
