common_args:
  training_type: "simulation"
  random_seed: 0
  config_version: "dev"
  mlops_api_key: c9356b9c4ce44363bb66366b210201
  mlops_project_name: simulation_2
  mlops_run_name: fedml_torch_fedavg_COCP
  active: 0
  var_epoch: 0
  overlap_percentage: 0.2
  alpha_dirichlet: 10000
  alpha_active: 1.0

data_args:
  dataset: "cifar10"
  data_cache_dir: ~/fedml_data
  partition_method: "hetero"
  partition_alpha: 0.5
  


model_args:
  model: "resnet_18"

train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[]"
  client_num_in_total: 12
  client_num_per_round: 12
  num_groups: 3
  comm_round: 20 # 3 is for quick GitHub sanity check. please change this to your own hyper-parameters (e.g., 200)
  epochs: 10
  batch_size: 128
  client_optimizer: adam
  learning_rate: .00001
  weight_decay: 0.0
  momentum: 0.9

validation_args:
  frequency_of_the_test: 1

device_args:
  using_gpu: true
  gpu_id: 0

comm_args:
  backend: "sp"

tracking_args:
  enable_tracking: false
   # When running on MLOps platform(open.fedml.ai), the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_wandb: true
  wandb_key: d99d2566208f899b41fe157bc466bece6d1789e2
  wandb_entity: shubham22124
  wandb_project: Cyclic and Overlapping Client Client Participation in Federated Setting
  run_name: randsamp_E10_R20_LRe-4_DEC0_adam_rsnt18_cfar10_homo_ALlPart
  using_mlops: false